### PR TITLE
Adding Library

### PR DESCRIPTION
**Pull request by jgimbel**
I wrote a simple library page. It shows what games the club has and has the ability to request to borrow a game.

### CODE REVIEW

**Comment by NathanBland** [comment]
@keawade Out of curiosity, is there a reason this hasn't been merged?

**Comment by keawade** [comment]
Ha, ha... Whaaaaa?

I may have gotten distracted before looking at it and then forgotten to come back to it, lol.

**Comment by jgimbel** [comment]
Its 3 commits keith, come on... Just make a dev branch for this

**Comment by NathanBland** [comment]
He merged it? What are you saying?

**Pull request merged**
